name: Backend Deployment

on:
  push:
    branches:
      - 11.x

jobs:
  run-script-on-ec2:
    runs-on: ubuntu-latest
    
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH and Deploy to Backend Server
       - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
       - name: Run Script on EC2
         env:
            EC2_USER: ${{ secrets.EC2_USER }}
            EC2_HOST: ${{ secrets.BACKEND_SERVER_IP }}
         script: |
            # Navigate to the Laravel app directory
            cd /var/www/backend-app

            # Pull the latest changes from the '11.x' branch
            git pull origin 11.x

            # Install composer dependencies without development packages and optimize the autoloader
            composer install --no-dev --optimize-autoloader

            # Run database migrations (with --force for production)
            php artisan migrate --force

            # Clear and cache config, routes, and views
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Set the correct file permissions for storage and cache directories
            sudo chown -R www-data:www-data /var/www/your-laravel-app/storage /var/www/your-laravel-app/bootstrap/cache
            sudo chmod -R 775 /var/www/your-laravel-app/storage /var/www/your-laravel-app/bootstrap/cache

            # Restart Nginx to reflect the new code (if using Nginx)
            sudo systemctl restart nginx
