name: Run Script on EC2

on:
  push:
    branches:
      - 11.x

jobs:
  run-script-on-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Script on EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Transfer the script to the EC2 instance
                   
          # Run the script on the EC2 instance
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "bash /tmp/hello.sh"
